version: "3.9"

services:

  api1:
    build:
      context: ./EBayCloneAPI
      dockerfile: Dockerfile
    container_name: ebay_api_1
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__MyCnn=Server=host.docker.internal,1433;Database=CloneEbayDB;User Id=sa;Password=123456;Encrypt=False;TrustServerCertificate=True
    volumes:
      - ./seed_data.sql:/app/seed_data.sql:ro
    restart: unless-stopped

  api2:
    build:
      context: ./EBayCloneAPI
      dockerfile: Dockerfile
    container_name: ebay_api_2
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__MyCnn=Server=host.docker.internal,1433;Database=CloneEbayDB;User Id=sa;Password=123456;Encrypt=False;TrustServerCertificate=True
    volumes:
      - ./seed_data.sql:/app/seed_data.sql:ro
    restart: unless-stopped

  web1:
    build:
      context: ./EbayCloneWeb
      dockerfile: Dockerfile
    container_name: ebay_web_1
    depends_on:
      - api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped

  web2:
    build:
      context: ./EbayCloneWeb
      dockerfile: Dockerfile
    container_name: ebay_web_2
    depends_on:
      - api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - api1
      - api2
    restart: unless-stopped

